docs: pin openstackdocstheme to < 3.4
Running sphinx 7.1.2 with openstackdocstheme >= 3.4 fails with the
following error:

Extension error (openstackdocstheme.page_context):
Handler <function html_page_context at 0x7a82a1c11d80> for event 'html-page-context' threw an exception (exception: 'str' object has no attribute 'relative_to')

We can't update Sphinx to at least 7.4, as this would require a python
version newer than 3.8, so with yoga we stick with the older
openstackdocstheme for now.